### ISSUE TITLE
per-second audiovisual quality scores always 5.0 even with corrupted video file

### ISSUE THREAD

**Issue by derbroti** [itu-p1203/itu-p1203#5] opened 2018-05-30 09:56 UTC
Hi,

is there a Bug or do I do something wrong?

I have a test-video with about 2200 of 14000 frames corrupted (i.e.: makroblocks and or slice header or parts of the both are replaced with the same amount of zerobytes (absolute offsets stay the same) -without- any audio stream and for "O22" i get "realistic" values lower than 5.0 - but for "O34" and "O35"i get a constant 5.0, although "O46" is realistic (a 4.x value) again.

I have not yet looked into the code but do you have any hints?

My issue is that the overall score is likely to be skewed due to the 5.0 in O34/35 right?

Cheers,
derbroti

**Comment by slhck** [comment] 2018-05-30 10:08
Due to the audiovisual integration function, if the audio score is 5, the video score has to be smaller than around 3.9 to produce an integrated audiovisual score of less than 5.

```
av1 = -0.00069084
av2 = 0.15374283
av3 = 0.97153861
av4 = 0.02461776

integrated = av1 + av2 * audio + av3 * video + av4 * audio * video
```

I would add that it is not considered valid to run the model on video data that has corrupted video frames.

**Comment by derbroti** [comment] 2018-05-30 10:46
I hope this is not a silly question: Is there a sensible way to "ignore" audio data and still get an overall score?

To the remark: would it produce  error-prone values on corrupted video?
Would you suggest to re-encode the video and feed the now valid video file - then only containing the artifacts as valid data into the tool?

**Comment by slhck** [comment] 2018-05-30 10:59
> Is there a sensible way to "ignore" audio data and still get an overall score?

Not officially, as the way the subjective studies for this model have been performed always included audio with the presentation. That means “hacking” the model to work on long files without audio would result in non-standard output.

In fact, in order to do that, one would have to change the audiovisual per-second integration function that I posted above, and instead *just* use the video quality value per second in O.34. This, again, would **not** be considered valid.

It is indeed unfortunate that the performance of the model with video-only input has not been characterized by the standardization group that created it, but a series of formal tests would be required in order to add new functionality to the standard. This would take a lot of time. The only intermediate step would be to provide an “enhanced” version of the model that modifies the bevhavior, which is backed up by some internal studies. I'll bring it up in a discussion.

> To the remark: would it produce error-prone values on corrupted video?

No, as the model has been trained on video degraded by compression only. The use case for this model is HTTP Adaptive Streaming with reliable transport, so packet loss can only lead to packet retransmissions and, eventually, stalling. Using the model on video degraded with packet loss or corrupted frames will yield invalid (and most likely too optimistic) results.

> Would you suggest to re-encode the video and feed the now valid video file - then only containing the artifacts as valid data into the tool?

No, for two reasons:

1. This would re-encode the video, making the usage of this kind of model invalid. The model works on either bitrate/resolution (in mode 0), or frame sizes (mode 1), or bitstream parameters (mode 2/3). These get changed when you re-encode.

2. The degradations of packet loss would not be visible to the model at all. (See the paragraph above.)

**Comment by slhck** [comment] 2018-08-01 15:11
I'm closing this as the behavior is as intended by the standard.

**Closed by slhck** 2018-08-01 15:11 UTC
Labels: question
